config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    validates :nombre, presence: true
    validates :apellido, presence: true
    validates :dni, presence: true
    validates :edad, presence: true
    validates :diadenacimiento, presence: true
    validates :mesdenacimiento, presence: true
    validates :aniodenacimiento, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :diadenacimiento, :mesdenacimiento, :aniodenacimiento, :edad, :dni)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>List</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">

      <!-- Custom fonts for this template-->
      <link
          href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">



  </head>

  <body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="<%= root_path %>">  
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="<%= usuarios_path %>">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Usuarios</span></a>
        </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <%= yield %>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

app/views/usuarios/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
    
      <%= form_with(model: usuario) do |form| %>
        <% if usuario.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>
      
            <ul>
              <% usuario.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      
        <div>
          <%= form.label :nombre, style: "display: block" %>
          <%= form.text_field :nombre, placeholder: 'Nombre' %>
        </div>
      
        <div>
          <%= form.label :apellido, style: "display: block" %>
          <%= form.text_field :apellido, placeholder: 'Apellido' %>
        </div>
      
        <div>
          <%= form.label :diadenacimiento, style: "display: block" %>
          <%= form.text_field :diadenacimiento, placeholder: 'Día' %>
        </div>

        <div>
          <%= form.label :mesdenacimiento, style: "display: block" %>
          <%= form.text_field :mesdenacimiento, placeholder: 'Mes' %>
        </div>

        <div>
          <%= form.label :aniodenacimiento, style: "display: block" %>
          <%= form.text_field :aniodenacimiento, placeholder: 'Año' %>
        </div>
      
        <div>
          <%= form.label :dni, style: "display: block" %>
          <%= form.text_field :dni, placeholder: 'DNI' %>
        </div>
      
        <div>
          <%= form.label :edad, style: "display: block" %>
          <%= form.text_field :edad, placeholder: 'Edad' %>
        </div>
      <br>
        <div>
          <%= form.submit "Enviar", class: 'btn btn-primary' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/usuarios/_usuario.html.erb
<div id="<%= dom_id usuario %>">
  <p>
    <strong>Nombre:</strong>
    <%= usuario.nombre %>
  </p>

  <p>
    <strong>Apellido:</strong>
    <%= usuario.apellido %>
  </p>

  <p>
    <strong>Diadenacimiento:</strong>
    <%= usuario.diadenacimiento %>
  </p>

  <p>
    <strong>Mesdenacimiento:</strong>
    <%= usuario.mesdenacimiento %>
  </p>

  <p>
    <strong>Aniodenacimiento:</strong>
    <%= usuario.aniodenacimiento %>
  </p>

  <p>
    <strong>Edad:</strong>
    <%= usuario.edad %>
  </p>

  <p>
    <strong>Dni:</strong>
    <%= usuario.dni %>
  </p>

</div>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Show this usuario", @usuario %> |
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<h1>Lista de Usuarios</h1>
<a href="<%= new_usuario_path %>" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
    <i class="fas fa-flag"></i>
  </span>
  <span class="text">Crear Usuario</span>
</a>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Edad</th>
    </tr>
  </thead>
  <tbody>
  <% @usuarios.each do |usuarios|%> 
    <tr>
      <td><%= usuarios.nombre %></td>
      <td><%= usuarios.apellido %></td>
      <td><%= usuarios.edad.to_i %></td>
      
      <td><%= link_to "Detalles", usuario_path(usuarios), class: 'btn btn-primary' %></td>
    </tr>
  <% end %>
  </tbody>
</table>
 <%
    edades=[25, 20, 50, 36, 50, 52, 39, 26, 21, 33 ].inject(0) {|sum,edades | sum+edades }
      %>
<h6> El promedio de edades entre los usuarios es:  <%= edades %></h6>
 <% mes=[1,1,3,4,4,5,7,7,9,10]
 personas=["Rodrigo", "Joey", "Andrea", "Miguel", "Luis Miguel", "Henry", "Julieta", "Anya", "Freya", "Marta"]
  zipped= mes.zip(personas)
  sorted=zipped.sort_by {|z| z.first}
  sorted.map(&:first) %>
  <h6>Orden por mes: <%= sorted %></h6>

app/views/usuarios/new.html.erb
<h1>Crea un Usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Regresar al listado de usuarios", usuarios_path, class: 'btn btn-primary' %>
  <br>
</div>

app/views/usuarios/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles del Usuario</h1>
    <%= link_to "Regresar al listado de usuarios", usuarios_path, class: 'btn btn-primary' %>
    <%= link_to "Editar este usuario", edit_usuario_path(@usuario), class: 'btn btn-primary' %>
    <%= button_to "Eliminar usuario", @usuario, method: :delete, class: 'btn btn-danger' %>

    <div class="card">
      <table class="table>"
        <tr>
          <td><b>Nombre de usuario:</b></td>
          <td><%= @usuario.nombre %></td>
        </tr>
        <tr>
          <td><b>Apellido de usuario:</b></td>
          <td><%= @usuario.apellido %></td> 
        </tr>
        <tr>
          <td><b>Día de nacimiento:</b></td>
          <td><%= @usuario.diadenacimiento %></td> 
        </tr> 
        <tr>
          <td><b>Mes de nacimiento:</b></td>
          <td><%= @usuario.mesdenacimiento %></td> 
        </tr>
        <tr>
          <td><b>Año de nacimiento:</b></td>
          <td><%= @usuario.aniodenacimiento %></td> 
        </tr>
        <tr>
          <td><b>DNI:</b></td>
          <td><%= @usuario.dni %></td> 
        </tr>
      </table> 
    </div>
  
  </div>
</div>